// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Deriving a report row from the SRE agent's OWN report document.
//
// The agent used to do this mapping itself, in
// openchoreo/agents/sre-agent/src/clients/aep_reports.py: it spelled this
// endpoint's path, its field names, its classification vocabulary, and the
// Markdown layout of THIS console. None of that is OpenChoreo's business, and
// carrying it in an Apache-2.0 upstream repo made every AEP contract change a
// change to somebody else's project.
//
// So the agent now sends its report whole and this file does the mapping. The
// dividing line is the one the handoff already follows: the agent sends facts
// about its own analysis, and AEP decides what they mean and how they read.
//
// # Byte-identical on purpose
//
// The Markdown produced here matches what the Python produced, exactly, and the
// tests assert it against golden files generated by running that Python. It is
// worth keeping that way: `diagnosis` is what the console renders, and the
// escalated issue quotes the handoff's own reasoning out of it
// (escalate.go's handoffReasoning).
//
// It used to matter far more. escalate.go recovered the recommended actions from
// this Markdown by anchored regex, so a stray space here silently stopped
// escalation — an undocumented text format acting as a contract between two
// repositories. The actions now arrive as fields and that regex is gone, which
// downgrades a rendering slip from "escalation stops" to "a page reads worse".
package createreport

import (
	"fmt"
	"math"
	"strings"

	"github.com/wso2/aep/aep-api/internal/ops"
)

// Field caps, carried over verbatim from the Python. They bound a row and the
// notification-bell payload rather than expressing anything about the report.
const (
	maxTitle     = 200
	maxExcerpt   = 500
	maxDiagnosis = 20_000
)

// pyStr renders a decoded JSON value the way Python's str() would, because that
// is what produced the strings this must match. The nil case is deliberate:
// Python interpolates a missing key as "None", and a faithful port says "None"
// too rather than quietly emitting an empty string a reader cannot distinguish
// from a genuinely empty field.
func pyStr(v any) string {
	switch t := v.(type) {
	case nil:
		return "None"
	case string:
		return t
	case bool:
		if t {
			return "True"
		}
		return "False"
	case float64:
		if t == math.Trunc(t) && !math.IsInf(t, 0) {
			return fmt.Sprintf("%d", int64(t))
		}
		return fmt.Sprintf("%v", t)
	default:
		return fmt.Sprintf("%v", t)
	}
}

// truthy mirrors Python's own notion of it, which every `or {}` and `if x:` in
// the original relied on: absent, nil, "", 0 and an empty collection are all
// false. Porting these as `!= nil` checks would emit sections the Python omitted.
func truthy(v any) bool {
	switch t := v.(type) {
	case nil:
		return false
	case string:
		return t != ""
	case bool:
		return t
	case float64:
		return t != 0
	case map[string]any:
		return len(t) > 0
	case []any:
		return len(t) > 0
	default:
		return true
	}
}

func objAt(m map[string]any, key string) map[string]any {
	if v, ok := m[key].(map[string]any); ok {
		return v
	}
	return map[string]any{}
}

func listAt(m map[string]any, key string) []any {
	if v, ok := m[key].([]any); ok {
		return v
	}
	return nil
}

// strAt is the `x.get(key, "")` case: present-and-a-string, or empty. It is NOT
// pyStr — the original used a bare .get() with an empty default in these spots.
func strAt(m map[string]any, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

// truncRunes cuts to n CHARACTERS. Python slices strings by rune and these
// fields carry em-dashes and arrows from the agent's own prose, so a byte cut
// would both differ from the original and risk splitting a codepoint.
func truncRunes(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n])
}

// nativeClassification reads the handoff's derived classification, normalising
// the agent's StrEnum spelling (underscores) to this contract's (hyphens). An
// unrecognised value answers "none" rather than reaching the column: the read
// side treats this as a closed set.
func nativeClassification(report map[string]any) string {
	handoff := objAt(report, "handoff")
	raw := "none"
	if v := handoff["classification"]; truthy(v) {
		raw = pyStr(v)
	}
	raw = strings.ReplaceAll(raw, "_", "-")
	if validClassifications[raw] {
		return raw
	}
	return "none"
}

// nativeTitle is the Alerts row headline: the top root cause's one-sentence
// summary, falling back to the alert name so a no-root-cause report still says
// something.
func nativeTitle(report map[string]any) string {
	result := objAt(report, "result")
	if rcs := listAt(result, "root_causes"); len(rcs) > 0 {
		if rc, ok := rcs[0].(map[string]any); ok && truthy(rc["summary"]) {
			return truncRunes(pyStr(rc["summary"]), maxTitle)
		}
	}
	title := "RCA report"
	if v := objAt(report, "alert_context")["alert_name"]; truthy(v) {
		title = pyStr(v)
	}
	return truncRunes(title, maxTitle)
}

// renderDiagnosis builds the console's detail/stepper body as Markdown, from the
// structured report rather than a JSON dump so it reads as prose in the UI.
func renderDiagnosis(report map[string]any) string {
	result := objAt(report, "result")
	var lines []string

	if v := report["summary"]; truthy(v) {
		lines = append(lines, pyStr(v), "")
	}

	if rcs := listAt(result, "root_causes"); len(rcs) > 0 {
		lines = append(lines, "## Root causes")
		for i, raw := range rcs {
			rc, _ := raw.(map[string]any)
			header := fmt.Sprintf("%d. %s", i+1, strAt(rc, "summary"))
			if conf := rc["confidence"]; truthy(conf) {
				header += fmt.Sprintf(" _(confidence: %s)_", pyStr(conf))
			}
			lines = append(lines, header)
			if a := rc["analysis"]; truthy(a) {
				lines = append(lines, "   "+pyStr(a))
			}
		}
		lines = append(lines, "")
	}

	if v := result["explanation"]; truthy(v) {
		// The no_root_cause_identified branch.
		lines = append(lines, "## Analysis", pyStr(v), "")
	}

	actions := listAt(objAt(result, "recommendations"), "recommended_actions")
	if len(actions) > 0 {
		lines = append(lines, "## Recommended actions")
		for _, raw := range actions {
			action, _ := raw.(map[string]any)
			line := "- " + strAt(action, "description")
			if s := action["status"]; truthy(s) {
				line += fmt.Sprintf(" _(%s)_", pyStr(s))
			}
			lines = append(lines, line)
			if r := action["rationale"]; truthy(r) {
				lines = append(lines, "  "+pyStr(r))
			}
		}
		lines = append(lines, "")
	}

	// Before the timeline on purpose: this string is truncated from the END, so
	// the decision has to outrank the evidence supporting it.
	lines = append(lines, renderHandoffDecision(report)...)

	if timeline := listAt(result, "timeline"); len(timeline) > 0 {
		lines = append(lines, "## Timeline")
		for _, raw := range timeline {
			ev, _ := raw.(map[string]any)
			comp := ""
			if c := ev["component"]; truthy(c) {
				comp = fmt.Sprintf("[%s] ", pyStr(c))
			}
			lines = append(lines, fmt.Sprintf("- `%s` %s%s",
				strAt(ev, "timestamp"), comp, strAt(ev, "event")))
		}
		lines = append(lines, "")
	}

	return truncRunes(strings.TrimSpace(strings.Join(lines, "\n")), maxDiagnosis)
}

// renderHandoffDecision publishes the handoff's own reasoning.
//
// On a DECLINE this is the most consequential thing on the page: no issue was
// filed, so nothing was ever dispatched, and that reasoning used to die at the
// publish boundary — leaving the console asserting "no actionable remediation"
// directly beneath remediation's own list of code changes it wanted. Right or
// wrong, that reads as an incident the platform dropped.
func renderHandoffDecision(report map[string]any) []string {
	handoff := objAt(report, "handoff")
	if len(handoff) == 0 {
		return nil
	}
	actions := listAt(objAt(objAt(report, "result"), "recommendations"), "recommended_actions")

	lines := []string{"## Handoff decision", ""}
	lines = append(lines, "**Classification:** "+nativeClassification(report))
	if handoff["created_issue_number"] == nil {
		lines = append(lines, "",
			"No issue was filed for this alert, so no coding agent was dispatched.")
	}
	lines = append(lines, "")

	if v := handoff["rationale"]; truthy(v) {
		lines = append(lines, pyStr(v), "")
	}

	if ruled := listAt(handoff, "ruled_out"); len(ruled) > 0 {
		lines = append(lines, "### Recommended actions ruled out")
		for _, raw := range ruled {
			entry, _ := raw.(map[string]any)
			description := ""
			if idx, ok := intIndex(entry["index"]); ok && idx >= 0 && idx < len(actions) {
				if a, ok := actions[idx].(map[string]any); ok && truthy(a["description"]) {
					description = pyStr(a["description"])
				}
			}
			if description == "" {
				description = fmt.Sprintf("action[%s]", pyStr(entry["index"]))
			}
			lines = append(lines, "- **"+description+"**")
			reason := "unspecified"
			if r := entry["reason"]; truthy(r) {
				reason = pyStr(r)
			}
			justification := ""
			if j := entry["justification"]; truthy(j) {
				justification = pyStr(j)
			}
			lines = append(lines, fmt.Sprintf("  _%s_ — %s", reason, justification))
		}
		lines = append(lines, "")
	}

	if related := listAt(handoff, "related_issues"); len(related) > 0 {
		lines = append(lines, "### Related issues")
		for _, raw := range related {
			issue, _ := raw.(map[string]any)
			title := ""
			if t := issue["title"]; truthy(t) {
				title = pyStr(t)
			}
			label := strings.TrimSpace(fmt.Sprintf("#%s %s", pyStr(issue["number"]), title))
			url := ""
			if u := issue["url"]; truthy(u) {
				url = pyStr(u)
			}
			if url != "" {
				lines = append(lines, fmt.Sprintf("- [%s](%s)", label, url))
			} else {
				lines = append(lines, "- "+label)
			}
		}
		lines = append(lines, "")
	}

	return lines
}

// intIndex accepts the integral JSON number Python saw as an int. A fractional
// or non-numeric index is not an index, and is reported as such so the caller
// falls back to naming the position rather than silently picking action 0.
func intIndex(v any) (int, bool) {
	f, ok := v.(float64)
	if !ok || f != math.Trunc(f) || math.IsInf(f, 0) {
		return 0, false
	}
	return int(f), true
}

// nativeAction is one of the report's recommended actions, reduced to the two
// fields the escalation decision turns on. It is deliberately not the agent's
// full action model: this package needs to know what was recommended and whether
// remediation could express it as configuration, and mirroring the rest would be
// re-modelling a document another repository owns.
type nativeAction struct {
	Description string
	Status      string
}

// nativeActions reads the recommended actions out of the report.
//
// This is what replaced a regex over rendered Markdown. The status is the whole
// point of reading them: `suggested` means the remediation agent could NOT
// express the action as a ReleaseBinding change, which is what makes it
// code-level work somebody has to do.
func nativeActions(report map[string]any) []nativeAction {
	raw := listAt(objAt(objAt(report, "result"), "recommendations"), "recommended_actions")
	if len(raw) == 0 {
		return nil
	}
	out := make([]nativeAction, 0, len(raw))
	for _, item := range raw {
		action, ok := item.(map[string]any)
		if !ok {
			continue
		}
		out = append(out, nativeAction{
			Description: strAt(action, "description"),
			Status:      strAt(action, "status"),
		})
	}
	return out
}

// fromNative derives the row and checks it can actually be stored.
//
// The 400 names fields of the REPORT, not of this request, because that is what
// the caller can act on: an agent that sent a report missing its alert context
// cannot fix "project" — it has no such field — and would be left guessing.
// Title and classification are absent from the check on purpose; both resolve to
// a defined fallback, so neither can fail.
func fromNative(org string, report map[string]any) (*ops.RcaAgentReport, error) {
	out := reportFromNative(org, report)

	var missing []string
	if out.Project == "" {
		missing = append(missing, "alert_context.project")
	}
	if out.Summary == "" {
		missing = append(missing, "summary")
	}
	if out.Diagnosis == "" {
		// Nothing rendered at all: no summary, no root causes, no explanation,
		// no actions, no handoff, no timeline. That is not a report.
		missing = append(missing, "result (the report rendered no content)")
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("%w: report is missing required content: %v",
			ops.ErrInvalidReport, missing)
	}
	return out, nil
}

// providerFact reads one of OUR facts off the handoff record.
//
// `adopted` and `recurrence` are AEP's own answers to `ae_create_issue` — the
// agent stamps them from the wire and never interprets them, which is why it
// now carries them in an opaque `provider_facts` bag rather than as typed
// fields it would have to understand. Reading them here is the other half of
// that: the agent holds the values, and the side that knows what they MEAN
// reads them.
//
// The top-level fallback is for an agent older than that change, which sent
// them flat. It is a compatibility shim with a defined end: once no deployment
// runs an agent that predates `provider_facts`, the second lookup can go. It
// exists so the two repos can be rolled in either order — the same guarantee
// that was missing when this endpoint's flat body was removed in one step, and
// report publishing broke for as long as the agent build took.
func providerFact(handoff map[string]any, name string) any {
	if facts, ok := handoff["provider_facts"].(map[string]any); ok {
		if v, present := facts[name]; present {
			return v
		}
	}
	return handoff[name]
}

// reportFromNative maps the agent's report document onto the row.
//
// The issue fields ride together on `created_issue_number`, because that is the
// only evidence an issue EXISTS: a handoff can answer needs_code_change=true and
// still end its turn having filed nothing, and treating the classification as
// evidence would record a dispatch that never happened.
func reportFromNative(org string, report map[string]any) *ops.RcaAgentReport {
	alert := objAt(report, "alert_context")
	handoff := objAt(report, "handoff")

	out := &ops.RcaAgentReport{
		OrgID:          org,
		Project:        strAt(alert, "project"),
		Component:      strAt(alert, "component"),
		Title:          nativeTitle(report),
		Summary:        strAt(report, "summary"),
		Classification: nativeClassification(report),
		Diagnosis:      renderDiagnosis(report),
	}

	if n, ok := intIndex(handoff["created_issue_number"]); ok {
		num := int64(n)
		out.IssueNumber = &num
		if u := handoff["created_issue_url"]; truthy(u) {
			out.IssueURL = pyStr(u)
		}
		// The handoff's rationale is the best short "why this issue exists" we
		// have — HandoffResult carries no issue title or body.
		if r := handoff["rationale"]; truthy(r) {
			out.IssueExcerpt = truncRunes(pyStr(r), maxExcerpt)
		}
		out.Dispatched = truthy(providerFact(handoff, "adopted"))
		// Sent only when the handoff established it: 0 means "unknown", and
		// claiming a first attempt on behalf of an answer that carried none
		// would be a guess.
		if rec, ok := intIndex(providerFact(handoff, "recurrence")); ok && rec != 0 {
			out.Recurrence = rec
		}
	}

	return out
}
